### PR TITLE
Code cleanup and a fix for persistent JDP staging operations

### LINKED ISSUE #87: Transfers restored from disk after service restarts are not progressing.
When I start a transfer that has a long-running process (like retrieving files from tape via the JDP) and then restart the DTS, the transfer does not progress after the restart. Its status is still persistent in the service, and shows as "staging", for example, but the transfer task itself is not updated properly.

I can reproduce this issue by

1. using the `dtspy` script below to request a transfer
2. stopping and restarting the service in Spin
3. checking the status of the transfer
4. watching the logs (nothing)

```python
import dts
import os

def main():
    # connect to the DTS
    token = os.getenv('DTS_KBASE_DEV_TOKEN')
    dts_client = dts.Client(api_key = token,
                            server = "https://lb-dts.staging.kbase.us")
                            #server = "http://localhost:8080")
    xferId = dts_client.transfer(file_ids = ['JDP:52902893067c013e2b062315'],
                                 source = 'jdp',
                                 destination = 'kbase')
    print(f'Transfer ID: {xferId}')

if __name__ == '__main__':
    main()
```

### PR DESCRIPTION
**Pull request by jeff-cohere**
This PR does some minor reorganization, hopefully making code easier to follow. It also introduces a mechanism for Database implementations (e.g. JDP, KBase, NMDC) to save any information required to make their state persistent between service restarts. For example, this mechanism allows our JDP proxy to maintain a table mapping a UUID for a DTS staging operation to a JDP integer token used to retrieve the actual staging status.

I've also improved error checking and propagation in a few places, which helped me identify the cause of the issue (#87) indicating the need for the persistence mechanism above.
 
Closes #87

### CODE REVIEW

File: databases/jdp/database.go [hunk 1]
```diff
@@ -44,30 +46,330 @@ import (
...
+			Path:         md.Source.FilePath,
+			Date:         md.Source.Date,
+			AddedDate:    md.Source.AddedDate,
+			ModifiedDate: md.Source.ModifiedDate,
+			Size:         md.Source.FileSize,
+			Metadata:     md.Source.Metadata,
+			MD5Sum:       md.Source.MD5Sum,
+		}
+		resources[index] = dataResourceFromFile(file)
+		if resources[index].Path == "" || resources[index].Path == "/" { // permissions probem
```
Comment (ialarmedalien) [inline databases/jdp/database.go:219]: problem

File: databases/jdp/database.go [hunk 2]
```diff
@@ -44,30 +46,330 @@ import (
...
+			return databases.StagingStatusUnknown, err
+		}
+		statusForString := map[string]databases.StagingStatus{
+			"new":     databases.StagingStatusActive,
+			"pending": databases.StagingStatusActive,
+			"ready":   databases.StagingStatusSucceeded,
+		}
+		if status, ok := statusForString[jdpResult.Status]; ok {
+			return status, nil
+		} else {
```
Comment (ialarmedalien) [inline databases/jdp/database.go:333]: insert else / return comment here

Comment (ialarmedalien) [reply databases/jdp/database.go:333]: i.e. no need for the `else` after the `return`

**Review by ialarmedalien — APPROVED** [review]
